// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKsehMNeA-oWuF5Dbj_MyX5vFTeu030VE',
    appId: '1:862006808495:web:bd28235b117df4e2b8295a',
    messagingSenderId: '862006808495',
    projectId: 'projectmas-3588b',
    authDomain: 'projectmas-3588b.firebaseapp.com',
    storageBucket: 'projectmas-3588b.appspot.com',
    measurementId: 'G-5CMTGM30JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfCM3HEUtVLl32_LgN9lGO07SvVEkliM',
    appId: '1:862006808495:android:dd2e26921327db5db8295a',
    messagingSenderId: '862006808495',
    projectId: 'projectmas-3588b',
    storageBucket: 'projectmas-3588b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjq8Bga9J2FpMrYACi5XaWA3TaViWIzw',
    appId: '1:862006808495:ios:0fb54411f4f93647b8295a',
    messagingSenderId: '862006808495',
    projectId: 'projectmas-3588b',
    storageBucket: 'projectmas-3588b.appspot.com',
    iosClientId: '862006808495-mh2fa7sd94co7a2a53qlks5f69igei3k.apps.googleusercontent.com',
    iosBundleId: 'edu.gatech.cs8803',
  );
}
